### ISSUE TITLE
Revisar link form C4P

### ISSUE THREAD

**Issue by tonimc** [gdg-galicia/devfest.gdggalicia.com#6]
El link de este año es: https://docs.google.com/forms/d/e/1FAIpQLSfxLCyXuO9zuC3y8bKuX3qLxlnBNvQ-wzMHti_QF0ltPgKasg/closedform

**Comment by dovalin** [comment]
Pero ese link va a un form que ya está cerrado...

**Comment by dovalin** [comment]
La cierro de todas formas porque entiendo que no es un error
